# NatLibFi/KB maintenance strategy v2

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "test"
    pull-request-branch-name:
      separator: "-"
